# Generated by Django 5.0.3 on 2024-03-25 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='cretaed_by',
            new_name='creataed_by',
        ),
    ]
