# Generated by Django 5.0.3 on 2024-03-25 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_rename_assinged_to_task_assigned'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='assigned_to',
        ),
    ]
