# Generated by Django 5.0.3 on 2024-03-23 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_role_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_of_logins',
            field=models.BigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserLogins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now=True)),
                ('login_status', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
