# Generated by Django 5.0.3 on 2024-03-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_user_no_of_logins_userlogins'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogins',
            name='payload',
            field=models.TextField(null=True),
        ),
    ]
